return {}
-- local js_based_languages = {
--   'typescript',
--   'javascript',
--   'typescriptreact',
--   'javascriptreact',
--   'vue',
-- }
--
-- return {
--   'mfussenegger/nvim-dap',
--   dependencies = {
--     { 'nvim-neotest/nvim-nio' },
--     { 'rcarriga/nvim-dap-ui' },
--     -- Install the vscode-js-debug adapter
--     {
--       'microsoft/vscode-js-debug',
--       -- After install, build it and rename the dist directory to out
--       build = 'npm install --legacy-peer-deps --no-save && npm install cross-env --save-dev && npx gulp vsDebugServerBundle && node build.js',
--       version = '1.*',
--     },
--     {
--       'mxsdev/nvim-dap-vscode-js',
--       config = function()
--         ---@diagnostic disable-next-line: missing-fields
--         require('dap-vscode-js').setup {
--           -- Path of node executable. Defaults to $NODE_PATH, and then "node"
--           -- node_path = "node",
--
--           -- Path to vscode-js-debug installation.
--           debugger_path = vim.fn.resolve(vim.fn.stdpath 'data' .. '/lazy/vscode-js-debug'),
--
--           -- Command to use to launch the debug server. Takes precedence over "node_path" and "debugger_path"
--           -- debugger_cmd = { "js-debug-adapter" },
--
--           -- which adapters to register in nvim-dap
--           adapters = {
--             'chrome',
--             'pwa-node',
--             'pwa-chrome',
--             'pwa-msedge',
--             'pwa-extensionHost',
--             'node-terminal',
--           },
--
--           -- Path for file logging
--           -- log_file_path = "(stdpath cache)/dap_vscode_js.log",
--
--           -- Logging level for output to file. Set to false to disable logging.
--           -- log_file_level = false,
--
--           -- Logging level for output to console. Set to false to disable console output.
--           -- log_console_level = vim.log.levels.ERROR,
--         }
--       end,
--     },
--     {
--       'Joakker/lua-json5',
--       build = './install.sh',
--     },
--   },
--   opts = {},
--   config = function()
--     local dap = require 'dap'
--     local dapui = require 'dapui'
--
--     vim.keymap.set('n', '<Leader>du', dap.step_out, { desc = 'Step Out' })
--     vim.keymap.set('n', '<Leader>di', dap.step_into, { desc = 'Step Into' })
--     vim.keymap.set('n', '<Leader>do', dap.step_over, { desc = 'Step Over' })
--     vim.keymap.set('n', '<Leader>dj', dap.continue, { desc = 'Continue Debugging' })
--     vim.keymap.set('n', '<Leader>ds', dap.terminate, { desc = 'Stop Debugging' })
--
--     vim.keymap.set('n', '<Leader>drb', dap.clear_breakpoints, { desc = 'Remove All Breakpoints' })
--     vim.keymap.set('n', '<Leader>dp', dapui.toggle, { desc = 'Open Debug View' })
--
--     vim.keymap.set('n', '<Leader>deb', function()
--       dap.toggle_breakpoints(true)
--     end, { desc = 'Enable All Breakpoints' })
--
--     vim.keymap.set('n', '<Leader>ddb', function()
--       dap.toggle_breakpoints(false)
--     end, { desc = 'Disable All Breakpoints' })
--
--     vim.keymap.set('n', '<Leader>db', dap.toggle_breakpoint, { desc = 'Toggle Breakpoint' })
--
--     for _, language in ipairs(js_based_languages) do
--       dap.configurations[language] = {
--         -- Debug single nodejs files
--         {
--           type = 'pwa-node',
--           request = 'launch',
--           name = 'Launch file',
--           program = '${file}',
--           cwd = vim.fn.getcwd(),
--           sourceMaps = true,
--         },
--         -- Debug nodejs processes (make sure to add --inspect when you run the process)
--         {
--           type = 'pwa-node',
--           request = 'attach',
--           name = 'Attach',
--           processId = require('dap.utils').pick_process,
--           cwd = vim.fn.getcwd(),
--           sourceMaps = true,
--         },
--         -- Debug web applications (client side)
--         {
--           type = 'pwa-chrome',
--           request = 'launch',
--           name = 'Launch & Debug Chrome',
--           url = function()
--             local co = coroutine.running()
--             return coroutine.create(function()
--               vim.ui.input({
--                 prompt = 'Enter URL: ',
--                 default = 'http://localhost:3000',
--               }, function(url)
--                 if url == nil or url == '' then
--                   return
--                 else
--                   coroutine.resume(co, url)
--                 end
--               end)
--             end)
--           end,
--           webRoot = vim.fn.getcwd(),
--           protocol = 'inspector',
--           sourceMaps = true,
--           userDataDir = false,
--         },
--         -- Divider for the launch.json derived configs
--         {
--           name = '----- ↓ launch.json configs ↓ -----',
--           type = '',
--           request = 'launch',
--         },
--       }
--     end
--   end,
-- }
